This test just checks to see whether Katana can read and recreate the exception handling data.